apiVersion: v1
kind: Secret
metadata:
  name: scp-secrets
  namespace: scp
  labels:
    app.kubernetes.io/name: secure-context-protocol
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Flask Configuration
  FLASK_SECRET_KEY: "your-super-secret-key-change-this-in-production"
  
  # Enterprise Configuration
  SCP_BASE_URL: "https://your-domain.com"
  SCP_CALLBACK_URL_OVERRIDE: "https://your-domain.com"
  
  # Webhook Configuration
  SCP_ENABLE_WEBHOOKS: "true"
  SCP_WEBHOOK_URL: "https://your-webhook-endpoint.com/scp-events"
  SCP_WEBHOOK_SECRET: "your-webhook-secret-for-signature-verification"
  
  # OAuth Provider Credentials
  GOOGLE_CLIENT_ID: "your-google-client-id"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret"
  MICROSOFT_CLIENT_ID: "your-microsoft-client-id"
  MICROSOFT_CLIENT_SECRET: "your-microsoft-client-secret"